### ISSUE TITLE
request for Msc. thesis

### ISSUE THREAD

**Issue by zangowzidane** [SkoogyDan/Supervised-Machine-Learning-for-Space-Antenna-Performance-Prediction#1]
Hello Niels! Thanks for sharing your impressive codes! I was wondering if it is possible for you to share the Master thesis of your project? I just start to learn about ML in EM area and will appreciate a lot for your kind help!

**Comment by Niels-Skovgaard-Jensen** [comment]
hi @zangowzidane, thanks for taking an interest. I have added the pdf in the new commit [b886dc4](https://github.com/Niels-Skovgaard-Jensen/Supervised-Machine-Learning-for-Space-Antenna-Performance-Prediction/commit/b886dc4b8556f25e307a9c08faf15b79204eac0f). 

If you have any questions feel free to reach out!
